package cz.muni.fi.pv168.clockcard;

import java.awt.event.ActionEvent;
import java.util.logging.FileHandler;
import java.util.logging.Handler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.AbstractAction;

/**
 * Login form
 *
 * @author David Stein
 * @version 2011.0629
 */
public class LoginForm extends javax.swing.JFrame {

    /** Creates new form LoginForm */
    public LoginForm() {
        Logger clockCardLogger = Logger.getLogger("cz.muni.fi.pv168.clockcard");
        clockCardLogger.setLevel(Level.ALL);
        Handler lowHandler = null, mediumHandler = null, highHandler = null;

        try {
            lowHandler = new FileHandler("log/low.log", true);
            mediumHandler = new FileHandler("log/medium.log", true);
            highHandler = new FileHandler("log/high.log", true);
        } catch (Exception ex) {
        }

        lowHandler.setLevel(Level.ALL);
        mediumHandler.setLevel(Level.CONFIG);
        highHandler.setLevel(Level.WARNING);

        lowHandler.setFormatter(new SimpleFormatter());
        mediumHandler.setFormatter(new SimpleFormatter());
        highHandler.setFormatter(new SimpleFormatter());

        clockCardLogger.addHandler(lowHandler);
        clockCardLogger.addHandler(mediumHandler);
        clockCardLogger.addHandler(highHandler);

        initComponents();
        WorkerManager.getInstance().testingOn();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLoginAsWorker = new javax.swing.JButton();
        btnLoginAsManager = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        loginMenu = new javax.swing.JMenu();
        loginAsWorkerMenuItem = new javax.swing.JMenuItem();
        loginAsManagerMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Translation"); // NOI18N
        setTitle(bundle.getString("LoginForm.title")); // NOI18N

        btnLoginAsWorker.setAction(new LoginAsWorkerAction());
        btnLoginAsWorker.setText(bundle.getString("LoginForm.btnLoginAsWorker.text")); // NOI18N

        btnLoginAsManager.setAction(new LoginAsManagerAction());
        btnLoginAsManager.setMnemonic('M');
        btnLoginAsManager.setText(bundle.getString("LoginForm.btnLoginAsManager.text")); // NOI18N

        loginMenu.setMnemonic('L');
        loginMenu.setText(bundle.getString("LoginForm.loginMenu.text")); // NOI18N

        loginAsWorkerMenuItem.setAction(new LoginAsWorkerAction());
        loginAsWorkerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.ALT_MASK));
        loginAsWorkerMenuItem.setText(bundle.getString("LoginForm.loginAsWorkerMenuItem.text")); // NOI18N
        loginMenu.add(loginAsWorkerMenuItem);

        loginAsManagerMenuItem.setAction(new LoginAsManagerAction());
        loginAsManagerMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        loginAsManagerMenuItem.setText(bundle.getString("LoginForm.loginAsManagerMenuItem.text")); // NOI18N
        loginMenu.add(loginAsManagerMenuItem);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setText(bundle.getString("LoginForm.exitMenuItem.text")); // NOI18N
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        loginMenu.add(exitMenuItem);

        jMenuBar1.add(loginMenu);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setMnemonic('A');
        jMenuItem3.setText(bundle.getString("LoginForm.jMenuItem3.text")); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem3);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoginAsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoginAsWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btnLoginAsWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLoginAsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new AboutForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
    * @param args the command line arguments
    */
    private static LoginForm mainFrame ;
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginForm.mainFrame = new LoginForm();
                LoginForm.mainFrame.setVisible(true);
            }
        });
    }



    private class LoginAsWorkerAction extends AbstractAction{
        public void actionPerformed(ActionEvent e) {
                LoginForm.mainFrame.setVisible(false);
                new LoginWorkerDialog(mainFrame, enabled).setVisible(true);
            }
    }

    private class LoginAsManagerAction extends AbstractAction{
        public void actionPerformed(ActionEvent e) {
            LoginForm.mainFrame.setVisible(false);
            new LoginManagerDialog(mainFrame, enabled).setVisible(true);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginAsManager;
    private javax.swing.JButton btnLoginAsWorker;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem loginAsManagerMenuItem;
    private javax.swing.JMenuItem loginAsWorkerMenuItem;
    private javax.swing.JMenu loginMenu;
    // End of variables declaration//GEN-END:variables

}
